export { ReactComponent as LogoImage } from './logo.svg'
export { ReactComponent as ArrowIcon } from './arrow.svg'
export { ReactComponent as SearchIcon } from './search.svg'
export { ReactComponent as Building } from './building.svg'
export { ReactComponent as Museum } from './museum.svg'
